import {site,rooms,posts,pending} from '../data/site.mjs';
import {landing,benefits,dayMoments,reviews,homeAttractions} from '../data/landing.mjs';
export function renderHome({pic,link,booking,placeholder,title,location,esc}){
 const unknown=v=>esc(v??'확인 예정');
 const recommended=[rooms.find(r=>r.id==='201'),...rooms.filter(r=>r.id!=='201'&&r.photo)].filter(Boolean);
 const info=r=>[['객실 형태',r.type],['기준 인원',r.standard],['최대 인원',r.maximum],['주요 시설',r.facilities],['가격',r.weekday??'가격 문의']];
 const hero=landing.heroPhoto?`<img class="hero-img" src="${esc(landing.heroPhoto)}" alt="${esc(landing.heroAlt??'해든뷰에서 바라본 노을')}" width="1920" height="1280" fetchpriority="high" loading="eager">`:pic('sunset','바다 위로 내려앉는 노을 — 출처가 확인된 분위기용 사진, 실제 해든뷰 전망 아님','hero-img',true);
 return `<div class="landing">
 <section class="hero landing-hero" aria-label="여수 해든뷰 소개">${hero}<div class="hero-shade"></div><div class="hero-content wrap"><span class="eyebrow">YEOSU OCEAN VIEW STAY</span><h1>노을이 머무는 곳,<br>여수 해든뷰</h1><p>${site.subtitle}</p><div class="actions">${link('#recommended','객실 둘러보기','btn white')}<button class="btn gold" data-booking-open>지금 예약하기 ↗</button></div></div><div class="hero-bottom wrap"><span>SEA, SUNSET & YOUR STAY</span>${landing.heroPhoto?'':'<span class="photo-note">분위기용 대표 사진 · 해든뷰 실제 사진 준비 중</span>'}</div></section>
 <div class="quick-facts"><div class="wrap">${['여수 바다 전망','오동도 전망','청결한 객실','편안한 휴식'].map((t,i)=>`<span><i aria-hidden="true">${['≈','⌖','✧','☼'][i]}</i>${t}</span>`).join('')}</div></div>
 <section class="section wrap" id="benefits">${title('WHY HAEDEUNVIEW','좋은 여행의 시작,<br>편안하게 머무는 곳.','바다 가까이, 일상에서 조금 멀리.')}<div class="benefit-grid">${benefits.map(b=>`<article class="benefit"><span class="line-icon" aria-hidden="true">${b.icon}</span><h3>${b.title}</h3><p>${b.text}</p></article>`).join('')}</div>${link('/about/','해든뷰 더 알아보기 ↗','text-link')}</section>
 <section class="section sand-section" id="recommended"><div class="wrap">${title('SELECTED ROOM','나의 여행에 맞는 쉼을 찾아요','201호를 먼저 둘러보고, 여행 인원과 일정에 맞게 문의해주세요.','/rooms/','모든 객실 보기')}<div class="recommended-grid">${recommended.map(r=>`<article class="recommended-room"><div class="recommend-visual">${link('/rooms/'+r.id+'/',placeholder(r,true),'room-image-link')}<div class="photo-booking">${booking()}</div></div><div class="recommend-copy"><span class="eyebrow">HAEDEUNVIEW · ${r.floor}</span><h3>${r.name}</h3><p>${esc(r.summary??'함께하는 여행의 쉼표가 될 공간을 만나보세요.')}</p><dl class="recommend-facts">${info(r).map(([k,v])=>`<div><dt>${k}</dt><dd>${unknown(v)}</dd></div>`).join('')}</dl>${link('/rooms/'+r.id+'/','객실 상세 보기 ↗','btn navy')}</div></article>`).join('')}</div><p class="subtle">실제 객실 사진은 준비 중입니다. 인원·구조·시설은 정보 확인 후 업데이트 예정이며, 실제 사진이 확인되는 객실을 순차적으로 소개합니다.</p></div></section>
 <section class="section wrap" id="compare">${title('COMPARE YOUR STAY','9개의 객실, 한눈에 비교하기','날짜와 인원을 알려주시면 알맞은 객실과 요금을 안내해드립니다.')}<div class="compare-desktop"><table><caption class="sr-only">해든뷰 전체 객실 형태, 인원, 시설 및 가격 비교</caption><thead><tr>${['객실명','객실 형태','기준 인원','최대 인원','주요 시설','가격','상세 보기'].map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rooms.map(r=>`<tr><th scope="row">${r.name}</th>${info(r).map(([,v])=>`<td>${unknown(v)}</td>`).join('')}<td>${link('/rooms/'+r.id+'/',r.name+' 보기 ↗','text-link')}</td></tr>`).join('')}</tbody></table></div><div class="compare-mobile">${rooms.map(r=>`<article><h3>${r.name}</h3><dl>${info(r).map(([k,v])=>`<div><dt>${k}</dt><dd>${unknown(v)}</dd></div>`).join('')}</dl>${link('/rooms/'+r.id+'/',r.name+' 상세 보기 ↗','btn outline')}</article>`).join('')}</div><div class="compare-help"><p>우리에게 맞는 객실이 궁금하다면</p><button class="btn navy" data-booking-open>객실·가격 문의하기 ↗</button></div></section>
 <section class="section day-section" id="day"><div class="wrap">${title('A DAY AT HAEDEUNVIEW','계획은 조금 덜,<br>여유는 조금 더.','해든뷰에서 보내는 하루를 그려보세요.')}<div class="day-grid">${dayMoments.map(m=>`<article class="day-card"><figure>${m.actualPhoto?`<img src="${esc(m.actualPhoto)}" alt="해든뷰의 ${m.label} 풍경" loading="lazy" width="640" height="480">`:pic(m.photo,m.label+'의 휴식을 표현한 분위기용 바다 사진')}<figcaption>${m.actualPhoto?'해든뷰의 '+m.label:'분위기용 사진 · 실제 숙소 사진 아님'}</figcaption></figure><span class="eyebrow">${m.time} · ${m.label}</span><h3>${m.title}</h3><p>${m.text}</p></article>`).join('')}</div></div></section>
 <section class="section wrap" id="guest-stories">${title('GUEST STORIES','머문 자리의 이야기','확인된 실제 투숙 후기만 소개합니다.','/reviews/','후기 전체 보기')}<div class="grid three">${reviews.length?reviews.slice(0,3).map(r=>`<article class="review-card"><span class="rating" aria-label="5점 만점에 ${esc(r.rating)}점">${'★'.repeat(Math.min(5,Math.max(0,Number(r.rating))))}</span><p>${esc(r.text)}</p><dl>${[['이용 객실',r.room],['여행 유형',r.trip],['작성 시기',r.date]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></article>`).join(''):['첫 번째','두 번째','세 번째'].map(n=>`<article class="review-card empty"><span class="eyebrow">GUEST STORY</span><h3>고객 후기 준비 중</h3><p>${n} 여행 이야기를 기다립니다.</p><dl><div><dt>만족 표시</dt><dd>후기 등록 후 표시</dd></div><div><dt>이용 객실</dt><dd>확인 예정</dd></div><div><dt>여행 유형</dt><dd>확인 예정</dd></div><div><dt>작성 시기</dt><dd>확인 예정</dd></div></dl></article>`).join('')}</div></section>
 <section class="section sand-section" id="nearby"><div class="wrap">${title('AROUND YEOSU','머무는 동안, 여수를 만나다','산책과 바다, 여수의 풍경을 여행에 더해보세요.','/travel/','주변 관광지 전체 보기')}<div class="tour-grid">${homeAttractions.map(a=>`<article class="tour-card">${a.photo?`<img src="${esc(a.photo)}" srcset="${esc(a.small)} 480w, ${esc(a.photo)} 800w" sizes="(max-width:700px) 100vw, (max-width:1200px) 50vw, 25vw" alt="${esc(a.alt??a.name+' 풍경')}" width="800" height="600" loading="lazy">`:`<div class="tour-photo-pending" role="img" aria-label="${a.name} 실제 사진 준비 중">${a.name}<small>사진 준비 중</small></div>`}<div class="card-body"><h3>${a.name}</h3><p>${a.description}</p><dl><div><dt>이동 방법</dt><dd>${unknown(a.transport)}</dd></div><div><dt>거리·시간</dt><dd>${unknown(a.distance)}</dd></div></dl>${link('https://map.naver.com/p/search/'+encodeURIComponent('여수 '+a.name),'지도에서 확인','text-link',true)}${a.source?`<small class="photo-credit">${link(a.source,a.credit??'사진 출처','',true)}<br>${link(a.license,'라이선스','',true)} · 크기 축소·화면 크롭</small>`:''}</div></article>`).join('')}</div></div></section>
 <section class="section wrap" id="journal">${title('TRAVEL JOURNAL','여행을 준비하는 작은 이야기','','/blog/','여행 글 전체 보기')}<div class="grid three">${posts.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(p=>`<article class="blog-card"><a href="/blog/${p.slug}/">${pic(p.photo,p.title+' — 분위기용 대표 사진')}<div class="card-body"><span class="eyebrow">${p.category}</span><h3>${p.title}</h3><p class="blog-excerpt">${esc(p.excerpt??p.sections[0][1].split('. ')[0]+'.')}</p><time datetime="${p.date}">${p.date.replaceAll('-','.')}</time><span class="text-link">글 읽기 ↗</span></div></a></article>`).join('')}</div></section>
 <section class="section wrap no-top" id="find-us">${title('FIND US','바다 곁으로 오시는 길','','/location/','오시는 길 상세 안내')}${location()}<div class="home-parking"><strong>주차 안내</strong><p>${landing.parking??pending}. 주차 가능 여부와 위치는 방문 전 전화로 확인해주세요.</p></div></section>
 </div>`;
}
